name: secure_check
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  crypto: ^3.0.6
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  google_fonts: ^6.2.1
  hive_flutter: ^1.1.0
  iconsax: ^0.0.8
  intl: ^0.20.2
  zxcvbn: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
